
CREATE DATABASE hitch_db;
CREATE USER hitch_user WITH PASSWORD 'hitch_password';
GRANT ALL PRIVILEGES ON DATABASE hitch_db TO hitch_user;
-- \c hitch_db
GRANT ALL ON SCHEMA public TO hitch_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO hitch_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO hitch_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO hitch_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO hitch_user;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
