export const theme = {
  colors: {
    primary: '#F59E0B',
    primaryDark: '#D97706',
    primaryLight: '#FCD34D',
    secondary: '#3B82F6',
    secondaryDark: '#2563EB',
    secondaryLight: '#60A5FA',
    accent: '#FF6B6B',
    tokenGold: '#FBBF24',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
    info: '#3B82F6',
    background: '#F8FAFC',
    backgroundSecondary: '#F1F5F9',
    surface: '#FFFFFF',
    cardBg: '#FFFFFF',
    text: '#0F172A',
    textDark: '#0F172A',
    textSecondary: '#64748B',
    textGray: '#64748B',
    textTertiary: '#94A3B8',
    textLight: '#94A3B8',
    border: '#E2E8F0',
    borderLight: '#F1F5F9',
    overlay: 'rgba(0, 0, 0, 0.5)',
    overlayLight: 'rgba(0, 0, 0, 0.3)',
    white: '#FFFFFF',
    black: '#000000',
    rider: '#3B82F6',
    pilot: '#F59E0B',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    xxl: 20,
    full: 9999,
  },
  fontSize: {
    xs: 12,
    sm: 14,
    base: 16,
    lg: 18,
    xl: 20,
    xxl: 24,
    xxxl: 32,
    huge: 48,
  },
  fontWeight: {
    regular: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
    extrabold: '800',
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 5,
    },
    xl: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
      elevation: 8,
    },
  },
  animation: {
    fast: 150,
    normal: 300,
    slow: 500,
  },
};

// Export individual parts for destructuring imports
export const { colors, spacing, borderRadius, fontSize, fontWeight, shadows, animation } = theme;

// Export typography as an alias for fontSize + fontWeight
export const typography = {
  ...fontSize,
  ...fontWeight,
  sizes: fontSize,
  weights: fontWeight,
};

// Backward compatibility - direct access
export const {
  primary,
  primaryDark,
  secondary,
  accent,
  tokenGold,
  success,
  warning,
  error,
  background,
  cardBg,
  textDark,
  textGray,
  textLight,
  border,
  overlay,
  white,
  black,
} = theme.colors;